# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yarshure/github/libkcp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yarshure/github/libkcp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yarshure/github/libkcp/CMakeFiles /Users/yarshure/github/libkcp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yarshure/github/libkcp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fec_test

# Build rule for target.
fec_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fec_test
.PHONY : fec_test

# fast build rule for target.
fec_test/fast:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/build
.PHONY : fec_test/fast

#=============================================================================
# Target rules for targets named kcp_test

# Build rule for target.
kcp_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kcp_test
.PHONY : kcp_test

# fast build rule for target.
kcp_test/fast:
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/build
.PHONY : kcp_test/fast

fec.o: fec.cpp.o

.PHONY : fec.o

# target to build an object file
fec.cpp.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/fec.cpp.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/fec.cpp.o
.PHONY : fec.cpp.o

fec.i: fec.cpp.i

.PHONY : fec.i

# target to preprocess a source file
fec.cpp.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/fec.cpp.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/fec.cpp.i
.PHONY : fec.cpp.i

fec.s: fec.cpp.s

.PHONY : fec.s

# target to generate assembly for a file
fec.cpp.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/fec.cpp.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/fec.cpp.s
.PHONY : fec.cpp.s

fec_test.o: fec_test.cpp.o

.PHONY : fec_test.o

# target to build an object file
fec_test.cpp.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/fec_test.cpp.o
.PHONY : fec_test.cpp.o

fec_test.i: fec_test.cpp.i

.PHONY : fec_test.i

# target to preprocess a source file
fec_test.cpp.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/fec_test.cpp.i
.PHONY : fec_test.cpp.i

fec_test.s: fec_test.cpp.s

.PHONY : fec_test.s

# target to generate assembly for a file
fec_test.cpp.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/fec_test.cpp.s
.PHONY : fec_test.cpp.s

galois.o: galois.cpp.o

.PHONY : galois.o

# target to build an object file
galois.cpp.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois.cpp.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois.cpp.o
.PHONY : galois.cpp.o

galois.i: galois.cpp.i

.PHONY : galois.i

# target to preprocess a source file
galois.cpp.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois.cpp.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois.cpp.i
.PHONY : galois.cpp.i

galois.s: galois.cpp.s

.PHONY : galois.s

# target to generate assembly for a file
galois.cpp.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois.cpp.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois.cpp.s
.PHONY : galois.cpp.s

galois_noasm.o: galois_noasm.cpp.o

.PHONY : galois_noasm.o

# target to build an object file
galois_noasm.cpp.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois_noasm.cpp.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois_noasm.cpp.o
.PHONY : galois_noasm.cpp.o

galois_noasm.i: galois_noasm.cpp.i

.PHONY : galois_noasm.i

# target to preprocess a source file
galois_noasm.cpp.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois_noasm.cpp.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois_noasm.cpp.i
.PHONY : galois_noasm.cpp.i

galois_noasm.s: galois_noasm.cpp.s

.PHONY : galois_noasm.s

# target to generate assembly for a file
galois_noasm.cpp.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois_noasm.cpp.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois_noasm.cpp.s
.PHONY : galois_noasm.cpp.s

galois_table.o: galois_table.c.o

.PHONY : galois_table.o

# target to build an object file
galois_table.c.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois_table.c.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois_table.c.o
.PHONY : galois_table.c.o

galois_table.i: galois_table.c.i

.PHONY : galois_table.i

# target to preprocess a source file
galois_table.c.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois_table.c.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois_table.c.i
.PHONY : galois_table.c.i

galois_table.s: galois_table.c.s

.PHONY : galois_table.s

# target to generate assembly for a file
galois_table.c.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/galois_table.c.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/galois_table.c.s
.PHONY : galois_table.c.s

ikcp.o: ikcp.c.o

.PHONY : ikcp.o

# target to build an object file
ikcp.c.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/ikcp.c.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/ikcp.c.o
.PHONY : ikcp.c.o

ikcp.i: ikcp.c.i

.PHONY : ikcp.i

# target to preprocess a source file
ikcp.c.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/ikcp.c.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/ikcp.c.i
.PHONY : ikcp.c.i

ikcp.s: ikcp.c.s

.PHONY : ikcp.s

# target to generate assembly for a file
ikcp.c.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/ikcp.c.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/ikcp.c.s
.PHONY : ikcp.c.s

inversion_tree.o: inversion_tree.cpp.o

.PHONY : inversion_tree.o

# target to build an object file
inversion_tree.cpp.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/inversion_tree.cpp.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/inversion_tree.cpp.o
.PHONY : inversion_tree.cpp.o

inversion_tree.i: inversion_tree.cpp.i

.PHONY : inversion_tree.i

# target to preprocess a source file
inversion_tree.cpp.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/inversion_tree.cpp.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/inversion_tree.cpp.i
.PHONY : inversion_tree.cpp.i

inversion_tree.s: inversion_tree.cpp.s

.PHONY : inversion_tree.s

# target to generate assembly for a file
inversion_tree.cpp.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/inversion_tree.cpp.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/inversion_tree.cpp.s
.PHONY : inversion_tree.cpp.s

kcp_test.o: kcp_test.cpp.o

.PHONY : kcp_test.o

# target to build an object file
kcp_test.cpp.o:
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/kcp_test.cpp.o
.PHONY : kcp_test.cpp.o

kcp_test.i: kcp_test.cpp.i

.PHONY : kcp_test.i

# target to preprocess a source file
kcp_test.cpp.i:
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/kcp_test.cpp.i
.PHONY : kcp_test.cpp.i

kcp_test.s: kcp_test.cpp.s

.PHONY : kcp_test.s

# target to generate assembly for a file
kcp_test.cpp.s:
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/kcp_test.cpp.s
.PHONY : kcp_test.cpp.s

matrix.o: matrix.cpp.o

.PHONY : matrix.o

# target to build an object file
matrix.cpp.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/matrix.cpp.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/matrix.cpp.o
.PHONY : matrix.cpp.o

matrix.i: matrix.cpp.i

.PHONY : matrix.i

# target to preprocess a source file
matrix.cpp.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/matrix.cpp.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/matrix.cpp.i
.PHONY : matrix.cpp.i

matrix.s: matrix.cpp.s

.PHONY : matrix.s

# target to generate assembly for a file
matrix.cpp.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/matrix.cpp.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/matrix.cpp.s
.PHONY : matrix.cpp.s

reedsolomon.o: reedsolomon.cpp.o

.PHONY : reedsolomon.o

# target to build an object file
reedsolomon.cpp.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/reedsolomon.cpp.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/reedsolomon.cpp.o
.PHONY : reedsolomon.cpp.o

reedsolomon.i: reedsolomon.cpp.i

.PHONY : reedsolomon.i

# target to preprocess a source file
reedsolomon.cpp.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/reedsolomon.cpp.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/reedsolomon.cpp.i
.PHONY : reedsolomon.cpp.i

reedsolomon.s: reedsolomon.cpp.s

.PHONY : reedsolomon.s

# target to generate assembly for a file
reedsolomon.cpp.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/reedsolomon.cpp.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/reedsolomon.cpp.s
.PHONY : reedsolomon.cpp.s

sess.o: sess.cpp.o

.PHONY : sess.o

# target to build an object file
sess.cpp.o:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/sess.cpp.o
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/sess.cpp.o
.PHONY : sess.cpp.o

sess.i: sess.cpp.i

.PHONY : sess.i

# target to preprocess a source file
sess.cpp.i:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/sess.cpp.i
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/sess.cpp.i
.PHONY : sess.cpp.i

sess.s: sess.cpp.s

.PHONY : sess.s

# target to generate assembly for a file
sess.cpp.s:
	$(MAKE) -f CMakeFiles/fec_test.dir/build.make CMakeFiles/fec_test.dir/sess.cpp.s
	$(MAKE) -f CMakeFiles/kcp_test.dir/build.make CMakeFiles/kcp_test.dir/sess.cpp.s
.PHONY : sess.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fec_test"
	@echo "... kcp_test"
	@echo "... fec.o"
	@echo "... fec.i"
	@echo "... fec.s"
	@echo "... fec_test.o"
	@echo "... fec_test.i"
	@echo "... fec_test.s"
	@echo "... galois.o"
	@echo "... galois.i"
	@echo "... galois.s"
	@echo "... galois_noasm.o"
	@echo "... galois_noasm.i"
	@echo "... galois_noasm.s"
	@echo "... galois_table.o"
	@echo "... galois_table.i"
	@echo "... galois_table.s"
	@echo "... ikcp.o"
	@echo "... ikcp.i"
	@echo "... ikcp.s"
	@echo "... inversion_tree.o"
	@echo "... inversion_tree.i"
	@echo "... inversion_tree.s"
	@echo "... kcp_test.o"
	@echo "... kcp_test.i"
	@echo "... kcp_test.s"
	@echo "... matrix.o"
	@echo "... matrix.i"
	@echo "... matrix.s"
	@echo "... reedsolomon.o"
	@echo "... reedsolomon.i"
	@echo "... reedsolomon.s"
	@echo "... sess.o"
	@echo "... sess.i"
	@echo "... sess.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

